_wandb:
    value:
        cli_version: 0.25.1
        e:
            zqtf5op9vyode2mpit462ejdt5qexi1q:
                codePath: train_unmixingguided_wandb.py
                codePathLocal: train_unmixingguided_wandb.py
                cpu_count: 16
                cpu_count_logical: 32
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "7936183619584"
                        used: "292466790400"
                email: yimin.zhu530@gmail.com
                executable: /home/yimin_gsilab2/miniconda3/envs/yimin_gsilab/bin/python
                gpu: NVIDIA RTX A6000
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-fdaf5674-fa9f-6c91-aa23-37fab35b2774
                host: gsilab2-MS-7E51
                memory:
                    total: "132475789312"
                os: Linux-6.17.0-19-generic-x86_64-with-glibc2.39
                program: /home/yimin_gsilab2/upload2github_code/unmixing_guided_Mamba/train_unmixingguided_wandb.py
                python: CPython 3.10.14
                root: /home/yimin_gsilab2/upload2github_code/unmixing_guided_Mamba
                startedAt: "2026-04-02T01:03:58.815281Z"
                writerId: zqtf5op9vyode2mpit462ejdt5qexi1q
        m: []
        python_version: 3.10.14
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 71
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 71
            "3":
                - 1
                - 13
                - 16
            "4": 3.10.14
            "5": 0.25.1
            "6": 4.40.2
            "10":
                - 20
            "12": 0.25.1
            "13": linux-x86_64
dataset_index:
    value: 13
dataset_name:
    value: Tea
endm_num:
    value: 23
hidden_dim:
    value: 128
lr:
    value: 0.001
max_epoch:
    value: 500
query_lr:
    value: 0.0005
seed:
    value: 0
split_image:
    value: false
train_samples:
    value: 30
val_samples:
    value: 10
